import { BigBookChapter } from '@/types/bigbook-v2';

/**
 * The AA Tradition
 * 
 * Pages 565-568
 */

export const appendix_1: BigBookChapter = {
  id: 'appendix-1',
  title: 'The AA Tradition',
  pageRange: [565, 568],
  paragraphs: [
    {
      id: 'appendix-1-p1',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 1,
      content: 'To those now in its fold, Alcoholics Anonymous has made the difference between misery and sobriety, and often the difference between life and death. A.A. can, of course, mean just as much to uncounted alcoholics not yet reached.',
    },
    {
      id: 'appendix-1-p2',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 2,
      content: 'Therefore, no society of men and women ever had a more urgent NEED for continuous effectiveness and permanent unity. We alcoholics see that we must work together and hang together, else most of us will finally die alone.',
    },
    {
      id: 'appendix-1-p3',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 3,
      content: 'The "12 Traditions" of Alcoholics Anonymous are, we A.A.\'s believe, the best answers that our experience has yet given to those ever urgent questions, "How can A.A. best function?" and, "How can A.A. best stay whole and so survive?"',
    },
    {
      id: 'appendix-1-p4',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 4,
      content: 'On the next page, A.A.\'s "12 Traditions" are seen in their so-called "short form," the form in general use today. This is a condensed version of the original "long form" A.A. Traditions as first printed in 1946. Because the "long form" is more explicit and of possible historic value, it is also reproduced.',
    },
    {
      id: 'appendix-1-p5',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 5,
      content: 'One—Our common welfare should come first; personal recovery depends upon A.A. unity.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p6',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 6,
      content: 'Two—For our group purpose there is but one ultimate authority—a loving God as He may express Himself in our group conscience. Our leaders are but trusted servants; they do not govern.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p7',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 7,
      content: 'Three—The only requirement for A.A. membership is a desire to stop drinking.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p8',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 8,
      content: 'Four—Each group should be autonomous except in matters affecting other groups, or A.A. as a whole.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p9',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 9,
      content: 'Five—Each group has but one primary purpose—to carry its message to the alcoholic who still suffers.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p10',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 10,
      content: 'Six—An A.A. group ought never endorse, finance or lend the A.A. name to any related facility or outside enterprise; lest problems of money, property and prestige divert us from our primary purpose.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p11',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 11,
      content: 'Seven—Every A.A. group ought to be fully self-supporting, declining outside contributions.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p12',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 12,
      content: 'Eight—Alcoholics Anonymous should remain forever nonprofessional, but our service centers may employ special workers.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p13',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 13,
      content: 'Nine—A.A., as such, ought never be organized; but we may create service boards or committees directly responsible to those they serve.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p14',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 14,
      content: 'Ten—Alcoholics Anonymous has no opinion on outside issues; hence the A.A. name ought never be drawn into public controversy.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p15',
      chapterId: 'appendix-1',
      pageNumber: 563,
      order: 15,
      content: 'Eleven—Our public relations policy is based upon attraction rather than promotion; we need always maintain personal anonymity at the level of press, radio and films.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p16',
      chapterId: 'appendix-1',
      pageNumber: 564,
      order: 16,
      content: 'Twelve—Anonymity is the spiritual foundation of all our Traditions, ever reminding us to place principles before personalities.',
      isItalic: true,
    },
    {
      id: 'appendix-1-p17',
      chapterId: 'appendix-1',
      pageNumber: 564,
      order: 17,
      content: '(The Long Form)',
    },
    {
      id: 'appendix-1-p18',
      chapterId: 'appendix-1',
      pageNumber: 564,
      order: 18,
      content: 'Our A.A. experience has taught us that:',
    },
    {
      id: 'appendix-1-p19',
      chapterId: 'appendix-1',
      pageNumber: 564,
      order: 19,
      content: '1.—Each member of Alcoholics Anonymous is but a small part of a great whole. A.A. must continue to live or most of us will surely die. Hence our common welfare comes first. But individual welfare follows close afterward.',
    },
    {
      id: 'appendix-1-p20',
      chapterId: 'appendix-1',
      pageNumber: 564,
      order: 20,
      content: '2.—For our group purpose there is but one ultimate authority—a loving God as He may express Himself in our group conscience.',
    },
    {
      id: 'appendix-1-p21',
      chapterId: 'appendix-1',
      pageNumber: 564,
      order: 21,
      content: '3.—Our membership ought to include all who suffer from alcoholism. Hence we may refuse none who wish to recover. Nor ought A.A. membership ever depend upon money or conformity. Any two or three alcoholics gathered together for sobriety may call themselves an A.A. Group, provided that, as a group, they have no other affiliation.',
    },
    {
      id: 'appendix-1-p22',
      chapterId: 'appendix-1',
      pageNumber: 564,
      order: 22,
      content: '4.—With respect to its own affairs, each A.A. group should be responsible to no other authority than its own conscience. But when its plans concern the welfare of neighboring groups also, those groups ought to be consulted. And no group, regional committee, or individual should ever take any action that might greatly affect A.A. as a whole without conferring with the Trustees of the General Service Board. On such issues our common welfare is paramount.',
    },
    {
      id: 'appendix-1-p23',
      chapterId: 'appendix-1',
      pageNumber: 564,
      order: 23,
      content: '5.—Each Alcoholics Anonymous group ought to be a spiritual entity HAVING BUT ONE PRIMARY PURPOSE—that of carrying its message to the alcoholic who still suffers.',
    },
    {
      id: 'appendix-1-p24',
      chapterId: 'appendix-1',
      pageNumber: 565,
      order: 24,
      content: '6.—Problems of money, property, and authority may easily divert us from our primary spiritual aim. We think, therefore, that any considerable property of genuine use to A.A. should be separately incorporated and managed, thus dividing the material from the spiritual. An A.A. group, as such, should never go into business. Secondary aids to A.A., such as clubs or hospitals which require much property or administration, ought to be incorporated and so set apart that, if necessary, they can be freely discarded by the groups. Hence such facilities ought not to use the A.A. name. Their management should be the sole responsibility of those people who financially support them. For clubs, A.A. managers are usually preferred. But hospitals, as well as other places of recuperation, ought to be well outside A.A.—and medically supervised. While an A.A. group may cooperate with anyone, such cooperation ought never go so far as affiliation or endorsement, actual or implied. An A.A. group can bind itself to no one.',
    },
    {
      id: 'appendix-1-p25',
      chapterId: 'appendix-1',
      pageNumber: 565,
      order: 25,
      content: '7.—The A.A. group themselves ought to be full supported by the voluntary contributions of their own members. We think that each group should soon achieve this ideal; that any public solicitation of funds using the name of Alcoholics Anonymous is highly dangerous, whether by groups, clubs, hospitals, or other outside agencies; that acceptance of large gifts from any source, or of contributions carrying any obligation whatever, is unwise. Then too, we view with much concern those A.A. treasuries which continue, beyond prudent reserves, to accumulate funds for no stated A.A. purpose. Experience has often warned us that nothing can so surely destroy our spiritual heritage as futile disputes over property, money, and authority.',
    },
    {
      id: 'appendix-1-p26',
      chapterId: 'appendix-1',
      pageNumber: 565,
      order: 26,
      content: '8.—Alcoholics Anonymous should remain forever nonprofessional. We define professionalism as the occupation of counseling alcoholics for fees or hire. But we may employ alcoholics where they are going to perform those services for which we might otherwise have to engage nonalcoholics. Such special services may be well recompensed. But our usual A.A. "12th Step" work is never to be paid for.',
    },
    {
      id: 'appendix-1-p27',
      chapterId: 'appendix-1',
      pageNumber: 567,
      order: 27,
      content: '9.—Each A.A. groups needs the least possible organization. Rotating leadership is the best. The small group may elect its Secretary, the large group its Rotating Committee, and the groups of a large Metropolitan area their Central or Intergroup Committee, which often employs a full-time Secretary. The trustees of the General Service Board are, in effect, our A.A. General Service Committee. They are the custodians of our A.A. Tradition and the receivers of voluntary A.A. contributions by which we maintain our A.A. General Service Office at New York. They are authorized by the groups to handle our over-all public relations and they guarantee the integrity of our principle newspaper, "The A.A. Grapevine." All such representatives are to be guided in the spirit of service, for true leaders in A. A. are but trusted and experienced servants of the whole. They derive no real authority from their titles; they do not govern. Universal respect is the key to their usefulness.',
    },
    {
      id: 'appendix-1-p28',
      chapterId: 'appendix-1',
      pageNumber: 567,
      order: 28,
      content: '10.—No A.A. group or member should ever, in such a way as to implicate A.A., express any opinion on outside controversial issues—particularly those of politics, alcohol reform, or sectarian religion. The Alcoholics Anonymous groups oppose no one. Concerning such matters they can express no views whatever.',
    },
    {
      id: 'appendix-1-p29',
      chapterId: 'appendix-1',
      pageNumber: 567,
      order: 29,
      content: '11.—Our relations with the general public should be characterized by personal anonymity. We think A.A. ought to avoid sensational advertising. Our names and pictures as A.A. members ought not be broadcast, filmed, or publicly printed. Our public relations should be guided by the principle of attraction rather than promotion. There is never need to praise ourselves. We feel it better to let our friends recommend us.',
    },
    {
      id: 'appendix-1-p30',
      chapterId: 'appendix-1',
      pageNumber: 567,
      order: 30,
      content: '12.—And finally, we of Alcoholics Anonymous believe that the principle of Anonymity has an immense spiritual significance. It reminds us that we are to place principles before personalities; that we are actually to practice a genuine humility. This to the end that our great blessings may never spoil us; that we shall forever live in thankful contemplation of Him who presides over us all.',
    }
  ],
};
