import { BigBookChapter } from '@/types/bigbook-v2';

/**
 * How It Works
 * Chapter 5
 * Pages 58-71
 */

export const chapter_5: BigBookChapter = {
  id: 'chapter-5',
  title: 'How It Works',
  chapterNumber: 5,
  pageRange: [58, 71],
  paragraphs: [
    {
      id: 'chapter-5-p1',
      chapterId: 'chapter-5',
      pageNumber: 58,
      order: 1,
      content: 'Rarely have we seen a person fail who has thoroughly followed our path. Those who do not recover are people who cannot or will not completely give themselves to this simple program, usually men and women who are constitutionally incapable of being honest with themselves. There are such unfortunates. They are not at fault; they seem to have been born that way. They are naturally incapable of grasping and developing a manner of living which demands rigorous honesty. Their chances are less than average. There are those, too, who suffer from grave emotional and mental disorders, but many of them do recover if they have the capacity to be honest.',
    },
    {
      id: 'chapter-5-p2',
      chapterId: 'chapter-5',
      pageNumber: 58,
      order: 2,
      content: 'Our stories disclose in a general way what we used to be like, what happened, and what we are like now. If you have decided you want what we have and are willing to go to any length to get it—then you are ready to take certain steps.',
    },
    {
      id: 'chapter-5-p3',
      chapterId: 'chapter-5',
      pageNumber: 58,
      order: 3,
      content: 'At some of these we balked. We thought we could find an easier, softer way. But we could not. With all the earnestness at our command, we beg of you to be fearless and thorough from the very start. Some of us have tried to hold on to our old ideas and the result was nil until we let go absolutely.',
    },
    {
      id: 'chapter-5-p4',
      chapterId: 'chapter-5',
      pageNumber: 58,
      order: 4,
      content: 'Remember that we deal with alcohol—cunning, baf-',
    },
    {
      id: 'chapter-5-p5',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 5,
      content: 'fling, powerful! Without help it is too much for us. But there is One who has all power—that One is God. May you find Him now!',
    },
    {
      id: 'chapter-5-p6',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 6,
      content: 'Half measures availed us nothing. We stood at the turning point. We asked His protection and care with complete abandon.',
    },
    {
      id: 'chapter-5-p7',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 7,
      content: 'Here are the steps we took, which are suggested as a program of recovery:',
    },
    {
      id: 'chapter-5-p8',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 8,
      content: '1. We admitted we were powerless over alcohol—that our lives had become unmanageable.',
    },
    {
      id: 'chapter-5-p9',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 9,
      content: '2. Came to believe that a Power greater than ourselves could restore us to sanity.',
    },
    {
      id: 'chapter-5-p10',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 10,
      content: '3. Made a decision to turn our will and our lives over to the care of God AS WE UNDERSTOOD HIM.',
    },
    {
      id: 'chapter-5-p11',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 11,
      content: '4. Made a searching and fearless moral inventory of ourselves.',
    },
    {
      id: 'chapter-5-p12',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 12,
      content: '5. Admitted to God, to ourselves, and to another human being the exact nature of our wrongs.',
    },
    {
      id: 'chapter-5-p13',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 13,
      content: '6. Were entirely ready to have God remove all these defects of character.',
    },
    {
      id: 'chapter-5-p14',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 14,
      content: '7. Humbly asked Him to remove our shortcomings.',
    },
    {
      id: 'chapter-5-p15',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 15,
      content: '8. Made a list of all persons we had harmed, and became willing to make amends to them all.',
    },
    {
      id: 'chapter-5-p16',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 16,
      content: '9. Made direct amends to such people wherever possible, except when to do so would injure them or others.',
    },
    {
      id: 'chapter-5-p17',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 17,
      content: '10. Continued to take personal inventory and when we were wrong promptly admitted it.',
    },
    {
      id: 'chapter-5-p18',
      chapterId: 'chapter-5',
      pageNumber: 59,
      order: 18,
      content: '11. Sought through prayer and meditation to improve our conscious contact with God AS WE UNDERSTOOD HIM, praying only for knowledge of His will for us and the power to carry that out.',
    },
    {
      id: 'chapter-5-p19',
      chapterId: 'chapter-5',
      pageNumber: 60,
      order: 19,
      content: '12. Having had a spiritual awakening as the result of these steps, we tried to carry this message to alcoholics, and to practice these principles in all our affairs.',
    },
    {
      id: 'chapter-5-p20',
      chapterId: 'chapter-5',
      pageNumber: 60,
      order: 20,
      content: 'Many of us exclaimed, "What an order! I can\'t go through with it." Do not be discouraged. No one among us has been able to maintain anything like perfect adherence to these principles. We are not saints. The point is, that we are willing to grow along spiritual lines. The principles we have set down are guides to progress. We claim spiritual progress rather than spiritual perfection.',
    },
    {
      id: 'chapter-5-p21',
      chapterId: 'chapter-5',
      pageNumber: 60,
      order: 21,
      content: 'Our description of the alcoholic, the chapter to the agnostic, and our personal adventure before and after make clear three pertinent ideas:',
    },
    {
      id: 'chapter-5-p22',
      chapterId: 'chapter-5',
      pageNumber: 60,
      order: 22,
      content: '(a) That we were alcoholic and could not manage our own lives.',
    },
    {
      id: 'chapter-5-p23',
      chapterId: 'chapter-5',
      pageNumber: 60,
      order: 23,
      content: '(b) That probably no human power could have relieved our alcoholism.',
    },
    {
      id: 'chapter-5-p24',
      chapterId: 'chapter-5',
      pageNumber: 60,
      order: 24,
      content: '(c) That God could and would if He were sought.',
    },
    {
      id: 'chapter-5-p25',
      chapterId: 'chapter-5',
      pageNumber: 60,
      order: 25,
      content: 'Being convinced, WE WERE AT STEP THREE, which is that we decided to turn our will and our life over to God as we understood Him. Just what do we mean by that, and just what do we do?',
    },
    {
      id: 'chapter-5-p26',
      chapterId: 'chapter-5',
      pageNumber: 60,
      order: 26,
      content: 'The first requirement is that we be convinced that any life run on self-will can hardly be a success. On that basis we are almost always in collision with something or somebody, even though our motives are good. Most people try to live by self-propulsion. Each person is like an actor who wants to run the whole show; is forever trying to arrange the lights, the ballet, the scenery and the rest of the players in his own way. If',
    },
    {
      id: 'chapter-5-p27',
      chapterId: 'chapter-5',
      pageNumber: 61,
      order: 27,
      content: 'his arrangements would only stay put, if only people would do as he wished, the show would be great. Everybody, including himself, would be pleased. Life would be wonderful. In trying to make these arrangements our actor may sometimes be quite virtuous. He may be kind, considerate, patient, generous; even modest and self-sacrificing. On the other hand, he may be mean, egotistical, selfish and dishonest. But, as with most humans, he is more likely to have varied traits.',
    },
    {
      id: 'chapter-5-p28',
      chapterId: 'chapter-5',
      pageNumber: 61,
      order: 28,
      content: 'What usually happens? The show doesn\'t come off very well. He begins to think life doesn\'t treat him right. He decides to exert himself more. He becomes, on the next occasion, still more demanding or gracious, as the case may be. Still the play does not suit him. Admitting he may be somewhat at fault, he is sure that other people are more to blame. He becomes angry, indignant, self-pitying. What is his basic trouble? Is he not really a self-seeker even when trying to be kind? Is he not a victim of the delusion that he can wrest satisfaction and happiness out of this world if he only manages well? Is it not evident to all the rest of the players that these are the things he wants? And do not his actions make each of them wish to retaliate, snatching all they can get out of the show? Is he not, even in his best moments, a producer of confusion rather than harmony?',
    },
    {
      id: 'chapter-5-p29',
      chapterId: 'chapter-5',
      pageNumber: 61,
      order: 29,
      content: 'Our actor is self-centered—ego-centric, as people like to call it nowadays. He is like the retired business man who lolls in the Florida sunshine in the winter complaining of the sad state of the nation; the minister who sighs over the sins of the twentieth century; politicians and reformers who are sure all would be Utopia',
    },
    {
      id: 'chapter-5-p30',
      chapterId: 'chapter-5',
      pageNumber: 62,
      order: 30,
      content: 'if the rest of the world would only behave; the outlaw safe cracker who thinks society has wronged him; and the alcoholic who has lost all and is locked up. Whatever our protestations, are not most of us concerned with ourselves, our resentments, or our self-pity?',
    },
    {
      id: 'chapter-5-p31',
      chapterId: 'chapter-5',
      pageNumber: 62,
      order: 31,
      content: 'Selfishness—self-centeredness! That, we think, is the root of our troubles. Driven by a hundred forms of fear, self-delusion, self-seeking, and self-pity, we step on the toes of our fellows and they retaliate. Sometimes they hurt us, seemingly without provocation, but we invariably find that at some time in the past we have made decisions based on self which later placed us in a position to be hurt.',
    },
    {
      id: 'chapter-5-p32',
      chapterId: 'chapter-5',
      pageNumber: 62,
      order: 32,
      content: 'So our troubles, we think, are basically of our own making. They arise out of ourselves, and the alcoholic is an extreme example of self-will run riot, though he usually doesn\'t think so. Above everything, we alcoholics must be rid of this selfishness. We must, or it kills us! God makes that possible. And there often seems no way of entirely getting rid of self without His aid. Many of us had moral and philosophical convictions galore, but we could not live up to them even though we would have liked to. Neither could we reduce our self-centeredness much by wishing or trying on our own power. We had to have God\'s help.',
    },
    {
      id: 'chapter-5-p33',
      chapterId: 'chapter-5',
      pageNumber: 62,
      order: 33,
      content: 'This is the how and the why of it. First of all, we had to quit playing God. It didn\'t work. Next, we decided that hereafter in this drama of life, God was going to be our Director. He is the Principal; we are His agents. He is the Father, and we are His children. Most good ideas are simple, and this concept was the keystone of the new and triumphant arch through which we passed to freedom.',
    },
    {
      id: 'chapter-5-p34',
      chapterId: 'chapter-5',
      pageNumber: 63,
      order: 34,
      content: 'When we sincerely took such a position, all sorts of remarkable things followed. We had a new Employer. Being all powerful, He provided what we needed, if we kept close to Him and performed His work well. Established on such a footing we became less and less interested in ourselves, our little plans and designs. More and more we became interested in seeing what we could contribute to life. As we felt new power flow in, as we enjoyed peace of mind, as we discovered we could face life successfully, as we became conscious of His presence, we began to lose our fear of today, tomorrow or the hereafter. We were reborn.',
    },
    {
      id: 'chapter-5-p35',
      chapterId: 'chapter-5',
      pageNumber: 63,
      order: 35,
      content: 'We were now at Step Three. Many of us said to our Maker, AS WE UNDERSTOOD HIM: "God, I offer myself to Thee—to build with me and to do with me as Thou wilt. Relieve me of the bondage of self, that I may better do Thy will. Take away my difficulties, that victory over them may bear witness to those I would help of Thy Power, Thy Love, and Thy Way of life. May I do Thy will always!" We thought well before taking this step making sure we were ready; that we could at last abandon ourselves utterly to Him.',
    },
    {
      id: 'chapter-5-p36',
      chapterId: 'chapter-5',
      pageNumber: 63,
      order: 36,
      content: 'We found it very desirable to take this spiritual step with an understanding person, such as our wife, best friend, or spiritual adviser. But it is better to meet God alone than with one who might misunderstand. The wording was, of course, quite optional so long as we expressed the idea, voicing it without reservation. This was only a beginning, though if honestly and humbly made, an effect, sometimes a very great one, was felt at once.',
    },
    {
      id: 'chapter-5-p37',
      chapterId: 'chapter-5',
      pageNumber: 63,
      order: 37,
      content: 'Next we launched out on a course of vigorous action, the first step of which is a personal housecleaning,',
    },
    {
      id: 'chapter-5-p38',
      chapterId: 'chapter-5',
      pageNumber: 64,
      order: 38,
      content: 'which many of us had never attempted. Though our decision was a vital and crucial step, it could have little permanent effect unless at once followed by a strenuous effort to face, and to be rid of, the things in ourselves which had been blocking us. Our liquor was but a symptom. So we had to get down to causes and conditions.',
    },
    {
      id: 'chapter-5-p39',
      chapterId: 'chapter-5',
      pageNumber: 64,
      order: 39,
      content: 'Therefore, we started upon a personal inventory. THIS WAS STEP FOUR. A business which takes no regular inventory usually goes broke. Taking commercial inventory is a fact-finding and a fact-facing process. It is an effort to discover the truth about the stock-in-trade. One object is to disclose damaged or unsalable goods, to get rid of them promptly and without regret. If the owner of the business is to be successful, he cannot fool himself about values.',
    },
    {
      id: 'chapter-5-p40',
      chapterId: 'chapter-5',
      pageNumber: 64,
      order: 40,
      content: 'We did exactly the same thing with our lives. We took stock honestly. First, we searched out the flaws in our make-up which caused our failure. Being convinced that self, manifested in various ways, was what had defeated us, we considered its common manifestations.',
    },
    {
      id: 'chapter-5-p41',
      chapterId: 'chapter-5',
      pageNumber: 64,
      order: 41,
      content: 'Resentment is the "number one" offender. It destroys more alcoholics than anything else. From it stem all forms of spiritual disease, for we have been not only mentally and physically ill, we have been spiritually sick. When the spiritual malady is overcome, we straighten out mentally and physically. In dealing with resentments, we set them on paper. We listed people, institutions or principles with whom we were angry. We asked ourselves why we were angry. In most cases it was found that our self-esteem, our pocketbooks, our ambitions, our personal relationships,',
    },
    {
      id: 'chapter-5-p42',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 42,
      content: '(including sex) were hurt or threatened. So we were sore. We were "burned up."',
    },
    {
      id: 'chapter-5-p43',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 43,
      content: 'On our grudge list we set opposite each name our injuries. Was it our self-esteem, our security, our ambitions, our personal, or sex relations, which had been interfered with?',
    },
    {
      id: 'chapter-5-p44',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 44,
      content: 'We were usually as definite as this example:',
    },
    {
      id: 'chapter-5-p45',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 45,
      content: '**I\'M RESENTFUL AT:** | **THE CAUSE** | **AFFECTS MY:**',
    },
    {
      id: 'chapter-5-p46',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 46,
      content: '---|---|---',
    },
    {
      id: 'chapter-5-p47',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 47,
      content: 'Mr. Brown | His attention to my wife. | Sex relations. Self-esteem (fear)',
    },
    {
      id: 'chapter-5-p48',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 48,
      content: '| Told my wife of my mistress. | Sex relations. Self-esteem (fear).',
    },
    {
      id: 'chapter-5-p49',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 49,
      content: '| Brown may get my job at the office. | Security. Self-esteem (fear).',
    },
    {
      id: 'chapter-5-p50',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 50,
      content: 'Mrs. Jones | She\'s a nut—she snubbed me. She committed her husband for drinking. He\'s my friend. She\'s a gossip. | Personal relationship. Self-esteem (fear).',
    },
    {
      id: 'chapter-5-p51',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 51,
      content: 'My employer | Unreasonable—Unjust—Overbearing—Threatens to fire me for drinking and padding my expense account. | Self-esteem (fear). Security.',
    },
    {
      id: 'chapter-5-p52',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 52,
      content: 'My wife | Misunderstands and nags. Likes Brown. Wants house put in her name. | Pride—Personal sex relations—Security (fear)',
    },
    {
      id: 'chapter-5-p53',
      chapterId: 'chapter-5',
      pageNumber: 65,
      order: 53,
      content: 'We went back through our lives. Nothing counted but thoroughness and honesty. When we were finished we considered it carefully. The first thing ap-',
    },
    {
      id: 'chapter-5-p54',
      chapterId: 'chapter-5',
      pageNumber: 66,
      order: 54,
      content: 'parent was that this world and its people were often quite wrong. To conclude that others were wrong was as far as most of us ever got. The usual outcome was that people continued to wrong us and we stayed sore. Sometimes it was remorse and then we were sore at ourselves. But the more we fought and tried to have our own way, the worse matters got. As in war, the victor only SEEMED to win. Our moments of triumph were short-lived.',
    },
    {
      id: 'chapter-5-p55',
      chapterId: 'chapter-5',
      pageNumber: 66,
      order: 55,
      content: 'It is plain that a life which includes deep resentment leads only to futility and unhappiness. To the precise extent that we permit these, do we squander the hours that might have been worth while. But with the alcoholic, whose hope is the maintenance and growth of a spiritual experience, this business of resentment is infinitely grave. We found that it is fatal. For when harboring such feelings we shut ourselves off from the sunlight of the Spirit. The insanity of alcohol returns and we drink again. And with us, to drink is to die.',
    },
    {
      id: 'chapter-5-p56',
      chapterId: 'chapter-5',
      pageNumber: 66,
      order: 56,
      content: 'If we were to live, we had to be free of anger. The grouch and the brainstorm were not for us. They may be the dubious luxury of normal men, but for alcoholics these things are poison.',
    },
    {
      id: 'chapter-5-p57',
      chapterId: 'chapter-5',
      pageNumber: 66,
      order: 57,
      content: 'We turned back to the list, for it held the key to the future. We were prepared to look for it from an entirely different angle. We began to see that the world and its people really dominated us. In that state, the wrong-doing of others, fancied or real, had power to actually kill. How could we escape? We saw that these resentments must be mastered, but how? We could not wish them away any more than alcohol.',
    },
    {
      id: 'chapter-5-p58',
      chapterId: 'chapter-5',
      pageNumber: 66,
      order: 58,
      content: 'This was our course: We realized that the people who wronged us were perhaps spiritually sick.',
    },
    {
      id: 'chapter-5-p59',
      chapterId: 'chapter-5',
      pageNumber: 67,
      order: 59,
      content: 'Though we did not like their symptoms and the way these disturbed us, they, like ourselves, were sick too. We asked God to help us show them the same tolerance, pity, and patience that we would cheerfully grant a sick friend. When a person offended we said to ourselves, "This is a sick man. How can I be helpful to him? God save me from being angry. Thy will be done."',
    },
    {
      id: 'chapter-5-p60',
      chapterId: 'chapter-5',
      pageNumber: 67,
      order: 60,
      content: 'We avoid retaliation or argument. We wouldn\'t treat sick people that way. If we do, we destroy our chance of being helpful. We cannot be helpful to all people, but at least God will show us how to take a kindly and tolerant view of each and every one.',
    },
    {
      id: 'chapter-5-p61',
      chapterId: 'chapter-5',
      pageNumber: 67,
      order: 61,
      content: 'Referring to our list again. Putting out of our minds the wrongs others had done, we resolutely looked for our own mistakes. Where had we been selfish, dishonest, self-seeking and frightened? Though a situation had not been entirely our fault, we tried to disregard the other person involved entirely. Where were we to blame? The inventory was ours, not the other man\'s. When we saw our faults we listed them. We placed them before us in black and white. We admitted our wrongs honestly and were willing to set these matters straight.',
    },
    {
      id: 'chapter-5-p62',
      chapterId: 'chapter-5',
      pageNumber: 67,
      order: 62,
      content: 'Notice that the word "fear" is bracketed alongside the difficulties with Mr. Brown, Mrs. Jones, the employer, and the wife. This short word somehow touches about every aspect of our lives. It was an evil and corroding thread; the fabric of our existence was shot through with it. It set in motion trains of circumstances which brought us misfortune we felt we didn\'t deserve. But did not we, ourselves, set the ball rolling? Sometimes',
    },
    {
      id: 'chapter-5-p63',
      chapterId: 'chapter-5',
      pageNumber: 68,
      order: 63,
      content: 'we think fear ought to be classed with stealing. It seems to cause more trouble.',
    },
    {
      id: 'chapter-5-p64',
      chapterId: 'chapter-5',
      pageNumber: 68,
      order: 64,
      content: 'We reviewed our fears thoroughly. We put them on paper, even though we had no resentment in connection with them. We asked ourselves why we had them. Wasn\'t it because self-reliance failed us? Self-reliance was good as far as it went, but it didn\'t go far enough. Some of us once had great self-confidence, but it didn\'t fully solve the fear problem, or any other. When it made us cocky, it was worse.',
    },
    {
      id: 'chapter-5-p65',
      chapterId: 'chapter-5',
      pageNumber: 68,
      order: 65,
      content: 'Perhaps there is a better way—we think so. For we are now on a different basis; the basis of trusting and relying upon God. We trust infinite God rather than our finite selves. We are in the world to play the role He assigns. Just to the extent that we do as we think He would have us, and humbly rely on Him, does He enable us to match calamity with serenity.',
    },
    {
      id: 'chapter-5-p66',
      chapterId: 'chapter-5',
      pageNumber: 68,
      order: 66,
      content: 'We never apologize to anyone for depending upon our Creator. We can laugh at those who think spirituality the way of weakness. Paradoxically, it is the way of strength. The verdict of the ages is that faith means courage. All men of faith have courage. They trust their God. We never apologize for God. Instead we let Him demonstrate, through us, what He can do. We ask Him to remove our fear and direct our attention to what He would have us be. At once, we commence to outgrow fear.',
    },
    {
      id: 'chapter-5-p67',
      chapterId: 'chapter-5',
      pageNumber: 68,
      order: 67,
      content: 'Now about sex. Many of us needed an overhauling there. But above all, we tried to be sensible on this question. It\'s so easy to get way off the track. Here we find human opinions running to extremes—absurd extremes, perhaps. One set of voices cry that sex is a lust of our lower nature, a base necessity of procrea-',
    },
    {
      id: 'chapter-5-p68',
      chapterId: 'chapter-5',
      pageNumber: 69,
      order: 68,
      content: 'tion. Then we have the voices who cry for sex and more sex; who bewail the institution of marriage; who think that most of the troubles of the race are traceable to sex causes. They think we do not have enough of it, or that it isn\'t the right kind. They see its significance everywhere. One school would allow man no flavor for his fare and the other would have us all on a straight pepper diet. We want to stay out of this controversy. We do not want to be the arbiter of anyone\'s sex conduct. We all have sex problems. We\'d hardly be human if we didn\'t. What can we do about them?',
    },
    {
      id: 'chapter-5-p69',
      chapterId: 'chapter-5',
      pageNumber: 69,
      order: 69,
      content: 'We reviewed our own conduct over the years past. Where had we been selfish, dishonest, or inconsiderate? Whom had we hurt? Did we unjustifiably arouse jealousy, suspicion or bitterness? Where were we at fault, what should we have done instead? We got this all down on paper and looked at it.',
    },
    {
      id: 'chapter-5-p70',
      chapterId: 'chapter-5',
      pageNumber: 69,
      order: 70,
      content: 'In this way we tried to shape a sane and sound ideal for our future sex life. We subjected each relation to this test—was it selfish or not? We asked God to mold our ideals and help us to live up to them. We remembered always that our sex powers were God-given and therefore good, neither to be used lightly or selfishly nor to be despised and loathed.',
    },
    {
      id: 'chapter-5-p71',
      chapterId: 'chapter-5',
      pageNumber: 69,
      order: 71,
      content: 'Whatever our ideal turns out to be, we must be willing to grow toward it. We must be willing to make amends where we have done harm, provided that we do not bring about still more harm in so doing. In other words, we treat sex as we would any other problem. In meditation, we ask God what we should do about each specific matter. The right answer will come, if we want it.',
    },
    {
      id: 'chapter-5-p72',
      chapterId: 'chapter-5',
      pageNumber: 69,
      order: 72,
      content: 'God alone can judge our sex situation. Counsel with',
    },
    {
      id: 'chapter-5-p73',
      chapterId: 'chapter-5',
      pageNumber: 70,
      order: 73,
      content: 'persons is often desirable, but we let God be the final judge. We realize that some people are as fanatical about sex as others are loose. We avoid hysterical thinking or advice.',
    },
    {
      id: 'chapter-5-p74',
      chapterId: 'chapter-5',
      pageNumber: 70,
      order: 74,
      content: 'Suppose we fall short of the chosen ideal and stumble? Does this mean we are going to get drunk? Some people tell us so. But this is only a half-truth. It depends on us and on our motives. If we are sorry for what we have done, and have the honest desire to let God take us to better things, we believe we will be forgiven and will have learned our lesson. If we are not sorry, and our conduct continues to harm others, we are quite sure to drink. We are not theorizing. These are facts out of our experience.',
    },
    {
      id: 'chapter-5-p75',
      chapterId: 'chapter-5',
      pageNumber: 70,
      order: 75,
      content: 'To sum up about sex: We earnestly pray for the right ideal, for guidance in each questionable situation, for sanity, and for the strength to do the right thing. If sex is very troublesome, we throw ourselves the harder into helping others. We think of their needs and work for them. This takes us out of ourselves. It quiets the imperious urge, when to yield would mean heartache.',
    },
    {
      id: 'chapter-5-p76',
      chapterId: 'chapter-5',
      pageNumber: 70,
      order: 76,
      content: 'If we have been thorough about our personal inventory, we have written down a lot. We have listed and analyzed our resentments. We have begun to comprehend their futility and their fatality. We have commenced to see their terrible destructiveness. We have begun to learn tolerance, patience and good will toward all men, even our enemies, for we look on them as sick people. We have listed the people we have hurt by our conduct, and are willing to straighten out the past if we can.',
    },
    {
      id: 'chapter-5-p77',
      chapterId: 'chapter-5',
      pageNumber: 70,
      order: 77,
      content: 'In this book you read again and again that faith did',
    },
    {
      id: 'chapter-5-p78',
      chapterId: 'chapter-5',
      pageNumber: 71,
      order: 78,
      content: 'for us what we could not do for ourselves. We hope you are convinced now that God can remove whatever self-will has blocked you off from Him. If you have already made a decision, and an inventory of your grosser handicaps, you have made a good beginning. That being so you have swallowed and digested some big chunks of truth about yourself.',
    }
  ],
};
