import { BigBookChapter } from '@/types/bigbook-v2';

/**
 * The Doctor's Opinion
 * Chapter 0
 * 
 * Pages xxiii–xxx (Roman numerals)
 */

export const doctors_opinion: BigBookChapter = {
  id: 'doctors-opinion',
  title: 'The Doctor\'s Opinion',
  chapterNumber: 0,
  pageRange: [23, 30],
  paragraphs: [
    {
      id: 'doctors-opinion-p1',
      chapterId: 'doctors-opinion',
      pageNumber: 23,
      order: 1,
      content: 'WE OF Alcoholics Anonymous believe that the reader will be interested in the medical estimate of the plan of recovery described in this book. Convincing testimony must surely come from medical men who have had experience with the sufferings of our members and have witnessed our return to health. A well-known doctor, chief physician at a nationally prominent hospital specializing in alcoholic and drug addiction, gave Alcoholics Anonymous this letter:',
    },
    {
      id: 'doctors-opinion-p2',
      chapterId: 'doctors-opinion',
      pageNumber: 23,
      order: 2,
      content: 'To Whom It May Concern:',
    },
    {
      id: 'doctors-opinion-p3',
      chapterId: 'doctors-opinion',
      pageNumber: 23,
      order: 3,
      content: 'I have specialized in the treatment of alcoholism for many years.',
    },
    {
      id: 'doctors-opinion-p4',
      chapterId: 'doctors-opinion',
      pageNumber: 23,
      order: 4,
      content: 'In late 1934 I attended a patient who, though he had been a competent businessman of good earning capacity, was an alcoholic of a type I had come to regard as hopeless.',
    },
    {
      id: 'doctors-opinion-p5',
      chapterId: 'doctors-opinion',
      pageNumber: 23,
      order: 5,
      content: 'In the course of his third treatment he acquired certain ideas concerning a possible means of recovery. As part of his rehabilitation he commenced to present his conceptions to other alcoholics, impressing upon them that they must do likewise with still others. This has become the basis of a rapidly growing fellowship of these men and their families. This man and over one hundred others appear to have recovered.',
    },
    {
      id: 'doctors-opinion-p6',
      chapterId: 'doctors-opinion',
      pageNumber: 23,
      order: 6,
      content: 'I personally know scores of cases who were of the type with whom other methods had failed completely.',
    },
    {
      id: 'doctors-opinion-p7',
      chapterId: 'doctors-opinion',
      pageNumber: 24,
      order: 7,
      content: 'These facts appear to be of extreme medical importance; because of the extraordinary possibilities of rapid growth inherent in this group they may mark a new epoch in the annals of alcoholism. These men may well have a remedy for thousands of such situations.',
    },
    {
      id: 'doctors-opinion-p8',
      chapterId: 'doctors-opinion',
      pageNumber: 24,
      order: 8,
      content: 'You may rely absolutely on anything they say about themselves.',
    },
    {
      id: 'doctors-opinion-p9',
      chapterId: 'doctors-opinion',
      pageNumber: 24,
      order: 9,
      content: 'Very truly yours,',
    },
    {
      id: 'doctors-opinion-p10',
      chapterId: 'doctors-opinion',
      pageNumber: 24,
      order: 10,
      content: 'William D. Silkworth, M.D.',
    },
    {
      id: 'doctors-opinion-p11',
      chapterId: 'doctors-opinion',
      pageNumber: 24,
      order: 11,
      content: 'The physician who, at our request, gave us this letter, has been kind enough to enlarge upon his views in another statement which follows. In this statement he confirms what we who have suffered alcoholic torture must believe - that the body of the alcoholic is quite as abnormal as his mind. It did not satisfy us to be told that we could not control our drinking just because we were maladjusted to life, that we were in full flight from reality, or were outright mental defectives. These things were true to some extent, in fact, to a considerable extent with some of us. But we are sure that our bodies were sickened as well. In our belief, any picture of the alcoholic which leaves out this physical factor is incomplete.',
    },
    {
      id: 'doctors-opinion-p12',
      chapterId: 'doctors-opinion',
      pageNumber: 24,
      order: 12,
      content: 'The doctor\'s theory that we have an allergy to alcohol interests us. As laymen, our opinion as to its soundness may, of course, mean little. But as ex-problem drinkers, we can say that his explanation makes good sense. It explains many things for which we cannot otherwise account.',
    },
    {
      id: 'doctors-opinion-p13',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 13,
      content: 'Though we work out our solutions on the spiritual as well as an altruistic plane, we favor hospitalization for the alcoholic who is very jittery or befogged. More often than not, it is imperative that a man\'s brain be cleared before he is approached, as he has then a better chance of understanding and accepting what we have to offer.',
    },
    {
      id: 'doctors-opinion-p14',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 14,
      content: 'The doctor writes:',
    },
    {
      id: 'doctors-opinion-p15',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 15,
      content: 'The subject presented in this book seems to me to be of paramount importance to those afflicted with alcoholic addiction.',
    },
    {
      id: 'doctors-opinion-p16',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 16,
      content: 'I say this after many years\' experience as Medical Director of one of the oldest hospitals in the country treating alcoholic and drug addiction.',
    },
    {
      id: 'doctors-opinion-p17',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 17,
      content: 'There was, therefore, a sense of real satisfaction when I was asked to contribute a few words on a subject which is covered in such masterly detail in these pages.',
    },
    {
      id: 'doctors-opinion-p18',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 18,
      content: 'We doctors have realized for a long time that some form of moral psychology was of urgent importance to alcoholics, but its application presented difficulties beyond our conception. What with our ultra-modern standards, our scientific approach to everything, we are perhaps not well equipped to apply the powers of good that lie outside our synthetic knowledge.',
    },
    {
      id: 'doctors-opinion-p19',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 19,
      content: 'Many years ago one of the leading contributors to this book came under our care in this hospital and while here he acquired some ideas which he put into practical application at once.',
    },
    {
      id: 'doctors-opinion-p20',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 20,
      content: 'Later, he requested the privilege of being allowed to tell his story to other patients here and with some misgiving, we consented. The cases we have followed through have been most interesting: in fact, many of them are amazing. The unselfishness of these men as we have come to know them, the entire absence of profit motive, and their community spirit, is indeed inspiring to one who has labored long and wearily in this alcoholic field. They believe in themselves, and still more in the Power which pulls chronic alcoholics back from the gates of death.',
    },
    {
      id: 'doctors-opinion-p21',
      chapterId: 'doctors-opinion',
      pageNumber: 26,
      order: 21,
      content: 'Of course an alcoholic ought to be freed from his physical craving for liquor, and this often requires a definite hospital procedure, before psychological measures can be of maximum benefit.',
    },
    {
      id: 'doctors-opinion-p22',
      chapterId: 'doctors-opinion',
      pageNumber: 26,
      order: 22,
      content: 'We believe, and so suggested a few years ago, that the action of alcohol on these chronic alcoholics is a manifestation of an allergy; that the phenomenon of craving is limited to this class and never occurs in the average temperate drinker. These allergic types can never safely use alcohol in any form at all; and once having formed the habit and found they cannot break it, once having lost their self-confidence, their reliance upon things human, their problems pile up on them and become astonishingly difficult to solve.',
    },
    {
      id: 'doctors-opinion-p23',
      chapterId: 'doctors-opinion',
      pageNumber: 26,
      order: 23,
      content: 'Frothy emotional appeal seldom suffices. The message which can interest and hold these alcoholic people must have depth and weight. In nearly all cases, their ideals must be grounded in a power greater than themselves, if they are to re-create their lives.',
    },
    {
      id: 'doctors-opinion-p24',
      chapterId: 'doctors-opinion',
      pageNumber: 26,
      order: 24,
      content: 'If any fell that as psychiatrists directing a hospital for alcoholics we appear somewhat sentimental, let them stand with us a while on the firing line, see the tragedies, the despairing wives, the little children; let the solving of these problems become a part of their daily work, and even of their sleeping moments, and the most cynical will not wonder that we have accepted and encouraged this movement. We feel, after many years of experience, that we have found nothing which has contributed more to the rehabilitation of these men than the altruistic movement now growing up among them.',
    },
    {
      id: 'doctors-opinion-p25',
      chapterId: 'doctors-opinion',
      pageNumber: 27,
      order: 25,
      content: 'Men and women drink essentially because they like the effect produced by alcohol. The sensation is so elusive that, while they admit it is injurious, they cannot after a time differentiate the true from the false. To them, their alcoholic life seems the only normal one. They are restless, irritable and discontented, unless they can again experience the sense of ease and comfort which comes at once by taking a few drinks - drinks which they see others taking with impunity. After they have succumbed to the desire again, as so many do, and the phenomenon of craving develops, they pass through the well-known stages of a spree, emerging remorseful, with a firm resolution not to drink again. This is repeated over and over, and unless this person can experience an entire psychic change there is very little hope of his recovery.',
    },
    {
      id: 'doctors-opinion-p26',
      chapterId: 'doctors-opinion',
      pageNumber: 27,
      order: 26,
      content: 'On the other hand - and strange as this may seem to those who do not understand once a psychic change has occurred, the very same person who seemed doomed, who had so many problems he despaired of ever solving them, suddenly finds himself easily able to control his desire for alcohol, the only effort necessary being that required to follow a few simple rules.',
    },
    {
      id: 'doctors-opinion-p27',
      chapterId: 'doctors-opinion',
      pageNumber: 27,
      order: 27,
      content: 'Men have cried out to me in sincere and despairing appeal: "Doctor, I cannot go on like this! I have everything to live for! I must stop, but I cannot! You must help me!"',
    },
    {
      id: 'doctors-opinion-p28',
      chapterId: 'doctors-opinion',
      pageNumber: 27,
      order: 28,
      content: 'Faced with this problem, if a doctor is honest with himself, he must sometimes feel his own inadequacy. Although he gives all that is in him, it often is not enough. One feels that something more than human power is needed to produce the essential psychic change. Though the aggregate of recoveries resulting from psychiatric effort is considerable, we physicians must admit we have made little impression upon the problem as a whole. Many types do not respond to the ordinary psychological approach.',
    },
    {
      id: 'doctors-opinion-p29',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 29,
      content: 'I do not hold with those who believe that alcoholism is entirely a problem of mental control. I have had many men who had, for example, worked a period of months on some problem or business deal which was to be settled on a certain date, favorably to them. They took a drink a day or so prior to the date, and then the phenomenon of craving at once became paramount to all other interests so that the important appointment was not met. These men were not drinking to escape; they were drinking to overcome a craving beyond their mental control.',
    },
    {
      id: 'doctors-opinion-p30',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 30,
      content: 'There are many situations which arise out of the phenomenon of craving which cause men to make the supreme sacrifice rather than continue to fight.',
    },
    {
      id: 'doctors-opinion-p31',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 31,
      content: 'The classification of alcoholics seems most difficult, and in much detail is outside the scope of this book. There are, of course, the psychopaths who are emotionally unstable. We are all familiar with this type. They are always "going on the wagon for keeps." They are over-remorseful and make many resolutions, but never a decision.',
    },
    {
      id: 'doctors-opinion-p32',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 32,
      content: 'There is the type of man who is unwilling to admit that he cannot take a drink. He plans various ways of drinking. He changes his brand or his environment. There is the type who always believes that after being entirely free from alcohol for a period of time he can take a drink without danger. There is the manic-depressive type, who is, perhaps, the least understood by his friends, and about whom a whole chapter could be written.',
    },
    {
      id: 'doctors-opinion-p33',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 33,
      content: 'Then there are types entirely normal in every respect except in the effect alcohol has upon them. They are often able, intelligent, friendly people.',
    },
    {
      id: 'doctors-opinion-p34',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 34,
      content: 'All these, and many others, have one symptom in common: they cannot start drinking without developing the phenomenon of craving. This phenomenon, as we have suggested, may be the manifestation of an allergy which differentiates these people, and sets them apart as a distinct entity. It has never been, by any treatment with which we are familiar, permanently eradicated. The only relief we have to suggest is entire abstinence.',
    },
    {
      id: 'doctors-opinion-p35',
      chapterId: 'doctors-opinion',
      pageNumber: 29,
      order: 35,
      content: 'This immediately precipitates us into a seething caldron of debate. Much has been written pro and con, but among physicians, the general opinion seems to be that most chronic alcoholics are doomed. What is the solution? Perhaps I can best answer this by relating one of my experiences.',
    },
    {
      id: 'doctors-opinion-p36',
      chapterId: 'doctors-opinion',
      pageNumber: 29,
      order: 36,
      content: 'About one year prior to this experience a man was brought in to be treated for chronic alcoholism. He had but partially recovered from a gastric hemorrhage and seemed to a case of pathological mental deterioration. He has lost everything worthwhile in life and was only living, one might say, to drink. He frankly admitted and believed that for him there was no hope. Following the elimination of alcohol, there was found to be no permanent brain injury. He accepted the plan outlined in this book. One year later he called to see me, and I experienced a very strange sensation. I knew the man by name, and partly recognized his features, but there all resemblance ended. From a trembling, despairing, nervous wreck, had emerged a man brimming over with self-reliance and contentment. I talked with him for some time, but was not able to bring myself to feel that I had known him before. To me he was a stranger, and so he left me. A long time has passed with no return to alcohol.',
    },
    {
      id: 'doctors-opinion-p37',
      chapterId: 'doctors-opinion',
      pageNumber: 29,
      order: 37,
      content: 'When I need a mental uplift, I often think of another case brought in by a physician prominent in New York. The patient had made his own diagnosis and deciding his situation hopeless, had hidden in a deserted barn determined to die. He was rescued by a searching party, and, in desperate condition, brought to me. Following his physical rehabilitation, he had a talk with me in which he frankly stated he thought the treatment a waste of effort, unless I could assure him, which no one ever had, that in the future he would have the "will power" to resist the impulse to drink.',
    },
    {
      id: 'doctors-opinion-p38',
      chapterId: 'doctors-opinion',
      pageNumber: 30,
      order: 38,
      content: 'His alcoholic problem was so complex and his depression so great, that we felt his only hope would be through what we then called "moral psychology", and we doubted if even that would have any effect. However, he did become "sold" on the ideas contained in this book. He has not had a drink for a great many years. I see him now and then and he is as fine a specimen of manhood as one could wish to meet.',
    },
    {
      id: 'doctors-opinion-p39',
      chapterId: 'doctors-opinion',
      pageNumber: 30,
      order: 39,
      content: 'I earnestly advise every alcoholic to read this book through, and though perhaps he came to scoff, he may remain to pray.',
    },
    {
      id: 'doctors-opinion-p40',
      chapterId: 'doctors-opinion',
      pageNumber: 30,
      order: 40,
      content: 'William D. Silkworth, M.D',
    },
  ],
};
