import { BigBookChapter } from '@/types/bigbook-v2';

/**
 * The Doctor's Opinion
 * 
 * Pages 23-32
 */

export const doctors_opinion: BigBookChapter = {
  id: 'doctors-opinion',
  title: 'The Doctor\'s Opinion',
  pageRange: [23, 32],
  paragraphs: [
    {
      id: 'doctors-opinion-p1',
      chapterId: 'doctors-opinion',
      pageNumber: 23,
      order: 1,
      content: '**Pages xxv–xxxii**',
    },
    {
      id: 'doctors-opinion-p2',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 2,
      content: 'We of Alcoholics Anonymous believe that the reader will be interested in the medical estimate of the plan of recovery described in this book. Convincing testimony must surely come from medical men who have had experience with the sufferings of our members and have witnessed our return to health. A well-known doctor, chief physician at a nationally prominent hospital specializing in alcoholic and drug addiction, gave Alcoholics Anonymous this letter:',
    },
    {
      id: 'doctors-opinion-p3',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 3,
      content: 'To Whom It May Concern:',
    },
    {
      id: 'doctors-opinion-p4',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 4,
      content: 'I have specialized in the treatment of alcoholism for many years. In late 1934 I attended a patient who, though he had been a competent businessman of good earning capacity, was an alcoholic of a type I had come to regard as hopeless.',
    },
    {
      id: 'doctors-opinion-p5',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 5,
      content: 'In the course of his third treatment he acquired certain ideas concerning a possible means of recovery. As part of his rehabilitation he commenced to present his conceptions to other alcoholics, impressing upon them that they must do likewise with still others. This has become the basis of a rapidly growing fellowship of these men and their families. This man and over one hundred others appear to have recovered.',
    },
    {
      id: 'doctors-opinion-p6',
      chapterId: 'doctors-opinion',
      pageNumber: 25,
      order: 6,
      content: 'I personally know scores of cases who were of the type with whom other methods had failed completely. These facts appear to be of extreme medical importance; because of the extraordinary possibilities of rapid growth inherent in this group, they may mark a new epoch. These men may well have a remedy for thousands of such situations.',
    },
    {
      id: 'doctors-opinion-p7',
      chapterId: 'doctors-opinion',
      pageNumber: 26,
      order: 7,
      content: 'You may rely absolutely on anything they say about themselves.',
    },
    {
      id: 'doctors-opinion-p8',
      chapterId: 'doctors-opinion',
      pageNumber: 26,
      order: 8,
      content: 'Very truly yours,',
    },
    {
      id: 'doctors-opinion-p9',
      chapterId: 'doctors-opinion',
      pageNumber: 26,
      order: 9,
      content: 'William D. Silkworth, M.D.',
    },
    {
      id: 'doctors-opinion-p10',
      chapterId: 'doctors-opinion',
      pageNumber: 26,
      order: 10,
      content: 'The physician who, at our request, gave us this letter has been kind enough to enlarge upon his views in another statement which follows.',
    },
    {
      id: 'doctors-opinion-p11',
      chapterId: 'doctors-opinion',
      pageNumber: 27,
      order: 11,
      content: 'In this statement he confirms what we who have suffered alcoholic torture must believe—that the body of the alcoholic is quite as abnormal as his mind. It did not satisfy us to be told that we could not control our drinking just because we were maladjusted to life, that we were in full flight from reality, or were outright mental defectives. These things were true to some extent, in fact, to a considerable extent with some of us. But we are sure that our bodies were sickened as well.',
    },
    {
      id: 'doctors-opinion-p12',
      chapterId: 'doctors-opinion',
      pageNumber: 27,
      order: 12,
      content: 'In our belief, any picture of the alcoholic which leaves out this physical factor is incomplete. The doctor’s theory that we have an allergy to alcohol interests us. As laymen, our opinion as to its soundness may, of course, mean little. But as ex-problem drinkers, we can say that his explanation makes good sense. It explains many things for which we cannot otherwise account.',
    },
    {
      id: 'doctors-opinion-p13',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 13,
      content: 'Though we work out our solution on the spiritual as well as an altruistic plane, we favor hospitalization for the alcoholic who is very jittery or befogged. More often than not, it is imperative that a man’s brain be cleared before he is approached, as he has then a better chance of understanding and accepting what we have to offer.',
    },
    {
      id: 'doctors-opinion-p14',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 14,
      content: 'The doctor writes:',
    },
    {
      id: 'doctors-opinion-p15',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 15,
      content: 'The subject presented in this book seems to me to be of paramount importance to those afflicted with alcoholic addiction.',
    },
    {
      id: 'doctors-opinion-p16',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 16,
      content: 'I say this after many years’ experience as Medical Director of one of the oldest hospitals in the country treating alcoholic and drug addiction. There is, therefore, a body of patients with whom I have been associated for many years. In this field I have seen many types of alcoholics. Of nearly all types, I have observed great numbers who have returned to normal.',
    },
    {
      id: 'doctors-opinion-p17',
      chapterId: 'doctors-opinion',
      pageNumber: 28,
      order: 17,
      content: 'There are, of course, the psychopaths who are emotionally unstable. We are all familiar with this type. He is always “going on the wagon for keeps.” He is over-remorseful and makes many resolutions, but never a decision.',
    },
    {
      id: 'doctors-opinion-p18',
      chapterId: 'doctors-opinion',
      pageNumber: 29,
      order: 18,
      content: 'There is the type of man who is unwilling to admit that he cannot take a drink. He plans various ways of drinking. He changes his brand or his environment. There is a type who always believes that after being entirely free from alcohol for a period of time he can take a drink without danger. There is the manic-depressive type, perhaps the least understood by his friends, about whom a whole chapter could be written.',
    },
    {
      id: 'doctors-opinion-p19',
      chapterId: 'doctors-opinion',
      pageNumber: 29,
      order: 19,
      content: 'Nor can we overlook the neurotic type. It is not always a question of psychopathic personality, in the sense that it is a breakdown of the personality. It has been suggested that this type of person is allergic to alcohol.',
    },
    {
      id: 'doctors-opinion-p20',
      chapterId: 'doctors-opinion',
      pageNumber: 29,
      order: 20,
      content: 'They are over-remorseful, and make many resolutions, but never a decision.',
    },
    {
      id: 'doctors-opinion-p21',
      chapterId: 'doctors-opinion',
      pageNumber: 29,
      order: 21,
      content: 'There is a type of man who is unwilling to admit that he cannot take a drink. He plans various ways of drinking. He changes his brand or his environment. He is always “going on the wagon for keeps.”',
    },
    {
      id: 'doctors-opinion-p22',
      chapterId: 'doctors-opinion',
      pageNumber: 29,
      order: 22,
      content: 'There is the manic-depressive type, perhaps the least understood by his friends, about whom a whole chapter could be written.',
    },
    {
      id: 'doctors-opinion-p23',
      chapterId: 'doctors-opinion',
      pageNumber: 29,
      order: 23,
      content: 'Nor can we overlook the neurotic type. It is not always a question of psychopathic personality, in the sense that it is a breakdown of the personality. It has been suggested that this type of person is allergic to alcohol.',
    },
    {
      id: 'doctors-opinion-p24',
      chapterId: 'doctors-opinion',
      pageNumber: 30,
      order: 24,
      content: 'About one third of our patients are of this class. The classification of alcoholics seems most difficult, and in actual practice it is not necessary. The lesson we have learned is that we must be entirely honest with ourselves.',
    },
    {
      id: 'doctors-opinion-p25',
      chapterId: 'doctors-opinion',
      pageNumber: 30,
      order: 25,
      content: 'There are men who have, for some reason, lost all power of choice in drink. Our so-called will power becomes practically nonexistent. We are unable, at certain times, to bring into our consciousness with sufficient force the memory of the suffering and humiliation of even a week or a month ago. We are without defense against the first drink.',
    },
    {
      id: 'doctors-opinion-p26',
      chapterId: 'doctors-opinion',
      pageNumber: 30,
      order: 26,
      content: 'The almost certain consequences that follow taking even a glass of beer do not crowd into the mind to deter us. If these thoughts occur, they are hazy and readily supplanted with the old threadbare idea that this time we shall handle ourselves like other people. There is a complete failure of the kind of defense that keeps one from putting his hand on a hot stove.',
    },
    {
      id: 'doctors-opinion-p27',
      chapterId: 'doctors-opinion',
      pageNumber: 30,
      order: 27,
      content: 'The alcoholic may say to himself in the most casual way, “It won’t burn me this time, so here’s how!” Or perhaps he doesn’t think at all. How often have some of us begun to drink in this nonchalant way, and after the third or fourth drink found ourselves on a spree?',
    },
    {
      id: 'doctors-opinion-p28',
      chapterId: 'doctors-opinion',
      pageNumber: 31,
      order: 28,
      content: 'If, when you honestly want to, you find you cannot quit entirely, or if, when drinking, you have little control over the amount you take, you are probably alcoholic. If that be the case, you may be suffering from an illness which only a spiritual experience will conquer.',
    },
    {
      id: 'doctors-opinion-p29',
      chapterId: 'doctors-opinion',
      pageNumber: 31,
      order: 29,
      content: 'To one who feels he is an atheist or agnostic, such an experience seems impossible, but to continue as he is means disaster. To be doomed to an alcoholic death or to live on a spiritual basis are not always easy alternatives to face.',
    },
    {
      id: 'doctors-opinion-p30',
      chapterId: 'doctors-opinion',
      pageNumber: 31,
      order: 30,
      content: 'But it isn’t so difficult. About half our original fellowship were of exactly that type. At first some of us tried to avoid the issue, hoping against hope we were not true alcoholics. But after a while we had to face the fact that we must find a spiritual basis of life—or else. Perhaps it is going to be that way with you. But cheer up, something like half of us thought we were atheists or agnostics. Our experience shows that you need not be disconcerted.',
    },
    {
      id: 'doctors-opinion-p31',
      chapterId: 'doctors-opinion',
      pageNumber: 32,
      order: 31,
      content: 'If a mere code of morals or a better philosophy of life were sufficient to overcome alcoholism, many of us would have recovered long ago. But we found that such codes and philosophies did not save us. No human power could have relieved our alcoholism. God could and would if He were sought.',
    },
    {
      id: 'doctors-opinion-p32',
      chapterId: 'doctors-opinion',
      pageNumber: 32,
      order: 32,
      content: 'William D. Silkworth, M.D.',
    }
  ],
};
